CREATE PROCEDURE DevolverIDMasReciente
AS
BEGIN
	DECLARE @ID INT = (SELECT TOP 1 Id_Sales FROM SALES_DETAILS ORDER BY 1 DESC)
	RETURN @ID;
END;

DECLARE @ID1 INT;
EXEC @ID1 = DevolverIDMasReciente;
SELECT @ID1;